services:
  rebrain-app:
    image: rebrain-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reBrain
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: reBrain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432